### PR TITLE
tax collector

### PR DESCRIPTION
**Pull request by NathanCrazy**
would be kinda funny

### CODE REVIEW

**Review by milenakos — APPROVED** [review]
this i s funny

**Comment by NathanCrazy** [comment]
mild issue taxes dont work

**Comment by milenakos** [comment]
you suck

**Comment by milenakos** [comment]
i should really stop accepting prs from u

**Comment by NathanCrazy** [comment]
i literally have no clue how this happened

**Comment by milenakos** [comment]
"i literally have no clue how this happened"
\- :nerd_face:

**Comment by therealten95** [comment]
interesting conversation

**Comment by milenakos** [comment]
okay update i tested it myself and taxes do work

**Comment by milenakos** [comment]
screw you nathaninsane

**Comment by milenakos** [comment]
oh wow im getting heated i should lock this

**Pull request merged**
