### PR TITLE
add more funny

### PR DESCRIPTION
**Pull request by uku1928**
I increased the size of funny by 66%

### CODE REVIEW

**Comment by MonkeysWithPie** [comment]
this is a very necessary change lia should merge it asap

**Comment by uku1928** [comment]
I wanted to make it 69% but the closest was 66% so I settled with that /j

**Comment by MonkeysWithPie** [comment]
simply add half of one (do not close the quotes) (make the entire cat bot source code a funny)

**Review by frinkifail — APPROVED** [review]
I don't see anything wrong with this

**Review by milenakos — APPROVED** [review]
ok

**Pull request merged**
