### PR TITLE
DAVE DISCORD 😀💀⚠️🥺

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Comment by MonkeysWithPie** [comment]
surely this will be accepted

**Comment by NathanCrazy** [comment]
i may have pushed it too far with this one

**Comment by therealten95** [comment]
DAVE DISCORD 😀💀⚠️🥺

**Review by milenakos — APPROVED** [review]
know what? whatever

**Comment by NathanCrazy** [comment]
i wish I could buy rains right now as a thank you but whatever
tysm
there will be no more stupid buttons like this

**Comment by uku1928** [comment]
I wonder when will someone get the 1 in more than 5 000 000

**Comment by NathanCrazy** [comment]
would be insane

**Pull request merged**
