### PR TITLE
what if we did the thing where the value and the total and the yes

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Comment by NathanCrazy** [comment]
round(what if we did the thing where the value and the total and the yes, 2)

as requested by blaumeise

**Comment by milenakos** [comment]
what

**Comment by milenakos** [comment]
this is a weird mix of #86 and some useless rarest leaderboard

**Comment by milenakos** [comment]
well im not merging rarest lb shit the rest seems good enough

**Comment by NathanCrazy** [comment]
rarest leaderboard was just badly named
that's just the cat value leaderboard

**Comment by milenakos** [comment]
:skull:

**Comment by milenakos** [comment]
well as we established im not gonna merge anything else from you so good night

**Comment by NathanCrazy** [comment]
> well as we established im not gonna merge anything else from you so good night

wait you actually meant that :staring_cat:
do you remember that the pr you replied with that to didn't actually break anything bc it was alr broken

**Comment by milenakos** [comment]
no i mean this pr is shit but thats a funnier close reason

**Comment by NathanCrazy** [comment]
why is it shit it looks fine 😭

**Comment by NathanCrazy** [comment]
you still never said why its shit

**Review by NathanCrazy — COMMENTED** [review]
i love github edit in place

**Comment by NathanCrazy** [comment]
thats the reason for all of those broken indents

**Comment by milenakos** [comment]
im not sure on whats the best way to present it, maybe like
`Total cats: {total}, with value: {value}`

**Comment by milenakos** [comment]
i feel like separate lines would look to weird but this doesnt feel less weird either

**Comment by milenakos** [comment]
`{total} cats with {value} value`?

**Comment by NathanCrazy** [comment]
yeah def that

**Comment by NathanCrazy** [comment]
9000 cats with 36000 value

**Comment by NathanCrazy** [comment]
i feel like it would look better with some word between {value} and value but idk
like total? combined? smth?

**Comment by milenakos** [comment]
is `total` variable even defined for trade embed?

**Comment by milenakos** [comment]
is it even useful?

**Comment by NathanCrazy** [comment]
it isnt defined whoopsies
its for seeing total number of cats in a trade
sack of cats wanted it

**Review by milenakos — APPROVED** [review]
unconvincingly approves

**Pull request merged**
