### PR TITLE
fix slot machine lock response inconsistency

### PR DESCRIPTION
**Pull request by VishramKidPG123**

### CODE REVIEW

**Comment by milenakos** [comment]
slots are assumed to be a part of the catsino

**Comment by VishramKidPG123** [comment]
why do they have separate locks then

**Comment by milenakos** [comment]
oh i remembered "out of the slot machine" sounds weird thats why

**Comment by VishramKidPG123** [comment]
how about "you get kicked from the slot machine"

**Comment by milenakos** [comment]
> how about "you get kicked from the slot machine"

yeah sounds good

**Pull request merged**
