### PR TITLE
Update the /supporter image already goddamit

### PR DESCRIPTION
**Pull request by rech2020**
if you dont like MY image you can replace it with your own

### CODE REVIEW

**Comment by rech2020** [comment]
i forfor

**Comment by uku1928** [comment]
yeah the old image is outdated, so I can see Milenakos update the image

**Comment by milenakos** [comment]
you should probably disable vencord or atleast stafftags

**Comment by rech2020** [comment]
Oh yea i forgot about that but i can't access the laptop now because it's getting late so

**Comment by milenakos** [comment]
im just gonna replace it on my own lol

**Pull request closed without merging**
