### PR TITLE
John Discord 🤠

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Comment by milenakos** [comment]
????

**Comment by NathanCrazy** [comment]
John Discord 🤠

**Comment by milenakos** [comment]
??????????????????????

**Comment by NathanCrazy** [comment]
(it would be funny to just have John Discord pop up instead of join discord tho)

**Comment by therealten95** [comment]
John Discord 🤠

**Comment by therealten95** [comment]
😢

**Comment by NathanCrazy** [comment]
he absolutely won't live on in our memories for more than like a month

**Pull request closed without merging**
