### PR TITLE
criminalize joy

### PR DESCRIPTION
**Pull request by NathanCrazy**

### CODE REVIEW

**Review by milenakos — CHANGES_REQUESTED** [review]
you very much need to define that variable in database.py schema
in this case just a local dict might work better though

**Comment by NathanCrazy** [comment]
you criminalized joy by moving to sql i cant just shit out random "cat types" like i have in basically every commit ive ever done

**Comment by NathanCrazy** [comment]
closed because lazy

**Comment by milenakos** [comment]
fuck you

**Comment by frinkifail** [comment]
why `int(user.criminality)`???

**Comment by milenakos** [comment]
> why `int(user.criminality)`???

bc stoopid

**Comment by NathanCrazy** [comment]
> > why `int(user.criminality)`???
> 
> bc stoopid

:True...:

**Comment by VishramKidPG123** [comment]
what did you do to the indentation

**Pull request closed without merging**
