### PR TITLE
NATHAN v2

### PR DESCRIPTION
**Pull request by NathanCrazy**
NATHANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
oh wait thats me

### CODE REVIEW

**Comment by milenakos** [comment]
what does this mean

**Comment by milenakos** [comment]
how the hell would you have negative or fractional placements what

**Comment by milenakos** [comment]
none of this makes any sense pleas ehelp

**Comment by NathanCrazy** [comment]
oh im stupid
i meant to make it round the value
:stored cat:

**Comment by milenakos** [comment]
oh

**Comment by milenakos** [comment]
you also forgor to remove interactor <= 0 in the first if

**Review by milenakos — APPROVED** [review]
aaaaaaaaaa

**Pull request merged**
